name: "Terraform: fmt (check)"
description: "Runs terraform fmt -check -recursive"

inputs:
  working-directory:
    description: "Terraform root directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: fmt check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform fmt -check -recursive


