name: "Terraform: init"
description: "Runs terraform init with a backend config file."

inputs:
  working-directory:
    description: "Terraform root directory"
    required: false
    default: "."
  backend-config:
    description: "Backend config file path (e.g. backend-dev.tfbackend)"
    required: true

runs:
  using: "composite"
  steps:
    - name: init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init -backend-config="${{ inputs.backend-config }}"
