name: "Terraform: apply (from plan)"
description: "Downloads a plan artifact and applies it."

inputs:
  working-directory:
    description: "Terraform root directory"
    required: false
    default: "."
  artifact-name:
    description: "Artifact name that contains the plan"
    required: false
    default: "tfplan"
  plan-file:
    description: "Plan filename"
    required: false
    default: "tfplan"
  auto-approve:
    description: "Whether to auto-approve"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: download plan
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}

    - name: apply
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.auto-approve }}" = "true" ]; then
          terraform apply -auto-approve "${{ inputs.plan-file }}"
        else
          terraform apply "${{ inputs.plan-file }}"
        fi


