name: "Terraform: plan (artifact)"
description: "Runs terraform plan and uploads the plan file as an artifact"

inputs:
  working-directory:
    description: "Terraform root directory"
    required: false
    default: "."
  var-file:
    description: "tfvars file (e.g. dev.tfvars)"
    required: true
  plan-file:
    description: "Output plan filename"
    required: false
    default: "tfplan"
  artifact-name:
    description: "Artifact name for the plan"
    required: false
    default: "tfplan"

runs:
  using: "composite"
  steps:
    - name: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform plan -var-file="${{ inputs.var-file }}" -out="${{ inputs.plan-file }}"

    - name: upload plan
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}/${{ inputs.plan-file }}


