name: "Cloud Build: build + push"
description: "Builds and pushes a container image using Google Cloud Build (gcloud builds submit)."

inputs:
  image:
    description: "Full image name (including tag)"
    required: true
  context:
    description: "Build context directory"
    required: false
    default: "."
  config:
    description: "Optional cloudbuild.yaml path"
    required: false
    default: ""
  timeout:
    description: "Cloud Build timeout (e.g. 900s)"
    required: false
    default: "900s"

runs:
  using: "composite"
  steps:
    - name: Build in Cloud Build
      shell: bash
      run: |
        if [ -n "${{ inputs.config }}" ]; then
          gcloud builds submit "${{ inputs.context }}" \
            --config="${{ inputs.config }}" \
            --timeout="${{ inputs.timeout }}"
        else
          gcloud builds submit "${{ inputs.context }}" \
            --tag="${{ inputs.image }}" \
            --timeout="${{ inputs.timeout }}"
        fi


