name: "Terraform: validate"
description: "Runs terraform validate."

inputs:
  working-directory:
    description: "Terraform root directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate


